server:
  port: 4321

spring:
  datasource:
    url: ENC(1YMfyXKmL7YWEcTHFzwPNiyq2GMZhsHvF/2k2V7cjr8blM5k9m+QmRXIzGPoemyqYXJvwCH4fZ9hK6wasA/SeIBTIfVvjdV3E0OGAy1ArZmLNIgH2vCLj/KOAPVpapYNFraKvpkU1DP1zsXtIQRCkAx0LMrRx6STODaIw4dbWJ2FrgPShfqiBD42l8A0+lt7IlkXR711o6LotXfFIDPoVg==)
    username: ENC(EHxw4u32ZnIC8/OP1Q4zcufnZNbCQHRSwVHNcgFyZ7nHD0LWREDEKSXPZsxradoR)
    password: ENC(w5J9agOfjPNYJnv8rGuZEp0xtM97Gc5BkUMP7TKrCZOmNz1iuV4X00HdsXbz+zys)

  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:**/mapper/*Mapper.xml
  #  config-location: classpath:mybatis/config/mybatis-config.xml
  configuration:
    auto-mapping-behavior: full

mybatis-plus:
  mapper-locations: classpath:**/mapper/*Mapper.xml

jasypt:
  encryptor:
    password: 12345678 #已经更改，启动项目需要更改为正确的盐
