server:
  port: 4321

spring:
  datasource:
    url: ENC(D4Bpa47bDpHBHo1Cke6SNyFs2tD6vSJvls8ltCJ13LFjliDekm7wEnd0qvgVN0IZrihlrMYrYPk+FTkTmTAcBKh61B32imoJDSYSSt8AYC0HYz8WAY05oiQjjr4+sI1CneWNQG/9yeLCcQ/RuEQ7ebvQXkEZbNdIh5r1tQmpfCbwRwAz8aRaGX+LpEAX4eZM)
    username: ENC(Rd+lbYob2cxepn7+i7v7NPneX1TI46EcWPSkZq1H9pyjS4UVoR79V1cFNua/krs7)
    password: ENC(h2qWkSxq5p9ypHldYMifU1LAq5b7cM1X4TcMcANWvvEMJ8kjDAdZYnT+V06S9L7u)

  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:**/mapper/*Mapper.xml
  #  config-location: classpath:mybatis/config/mybatis-config.xml
  configuration:
    auto-mapping-behavior: full

mybatis-plus:
  mapper-locations: classpath:**/mapper/*Mapper.xml

jasypt:
  encryptor:
    password: 12345678 #已经更改，启动项目需要更改为正确的盐
